const chissFam = [
    [`Mitth`, `Th`, 1],
    [`Ufsa`, `Sa`, 1],
    [`Irizi`, `Zi`, 1],
    [`Dasklo`, `Klo`, 1],
    [`Clarr`, `R`, 1],
    [`Chaf`, `F`, 1],
    [`Plikh`, `Kh`, 1],
    [`Boadil`, `Il`, 1],
    [`Obbic`, `Bic`, 1],
    
    [`Coduyo`, `Yo`, 2],
    [`Stybla`, `La`, 2],
    [`Xodlak`, `Lak`, 2],

    [`Droc`, `Oc`, 3],
    [`Kiwu`, `Wu`, 3],
    [`Pommrio`, `Rio`, 3],
    [`Erighal`, `Al`, 3],
    [`Tahmie`, `Mie`, 3],

    [`Brast`, `T`, 0],
    [`Cohbo`, `Bo`, 0],
    [`Csap`, `Ap`, 0],
    [`Daer`, `R`, 0],
    [`Elod`, `D`, 0],
    [`Evroes`, `Oes`, 0],
    [`Kivu`, `Vu`, 0],
    [`Krovi`, `Vi`, 0],
    [`Krovi`, `Vi`, 0],
    [`Kynkru`, `Ru`, 0],
    [`Tumaz`, `Az`, 0],
    [`Prard`, `D`, 0],
    // [`Csapla`, `Pla`, 4],
];

const chissGiv = [
    'Ab',
    'Al',
    'Alshi',
    'An',
    'Ar',
    'Ba',
    'Bet',
    'Che',
    'Dy',
    'Emo',
    'En',
    'Enc',
    'Ees',
    'Ers',
    'Etu',
    'Ey',
    'Ivl',
    'Iv',
    'Irv',
    'Ja',
    'Lia',
    'Mak',
    'Mi',
    'Ok',
    'Omo',
    'Oor',
    'Orm',
    'Os',
    'Par',
    'Po',
    'Ppin',
    'Upi',
    'Ras',
    'Raw',
    'Ro',
    'Rsi',
    'Tri',
    'Tro',
    'Urf',
    'Ykl',
    'Van',
];

const chissSoc = [
    ['nuru', 'n'],
    ['alani', 'a'],
    ['owmis', 'ow'],
    ['daro', 'da'],
    ['nifis', 'ni'],
    ['ro', 'ro'],
    ['titor', 'ti'],
    ['uhme', 'uh'],
    ['strob', 's'],
    ['sumf', 'su'],
    ['illmorf', 'ill'],
    ['nuf', 'n'],
    ['mustro', 'mu'],
    ['safis', 's'],
    ['omli', 'om'],
    ['astov', 'as'],
    ['to', 't'],
    ['begh', 'b'],
    ['kif', 'k'],
    ['nih', 'n'],
    ['gasoi', 'g'],
    ['barku', 'b'],
    ['aklio', 'a'],
    ['bintrano', 'bin'],
    ['uhme', 'uh'],
    ['ri', 'ri'],
    ['vilimt', 'vili'],
    ['exow', 'ex'],
    ['culry', 'cu'],
    ['ovmos', 'ov'],
    ['nekri', 'nek'],
    ['ath', 'a'],
    ['morhs', 'mo'],
    ['lothe', 'lo'],
    ['vumic', 'vu'],
    ['ikaro', 'ik'],
    ['mormi', 'm'],
    ['lacfo', 'l'],
    ['fosk', 'f'],
    ['ianico', 'ian'],
    ['omi', 'o'],
    ['iflar', 'if'],
    ['kleoni', 'k'],
    ['ovodo', 'ov'],
    ['cykok', 'cyk'],
    ['diamir', 'dia'],
];