const darths = [
    'Anthelion',
    'Nadirius',
    'Cisor',
    'Cognus',
    'Trudor',
    'Fernus',
    'Vestis',
    'Carceret',
    'Despotes',
    'Victus',
    'Cruxis',
    'Domitus',
    'Dustrius',
    'Fensus',
    'Flexus',
    'Visus',
    'Iratus',
    'Scivious',
    'Scarlot',
    'Valdis',
    'Holst',
    'Vanger',
    'Tchaiko',
    'Desch',
    'Kaber',
    'Amadius',
    'Hoven',
    'Shern',
    'Ghulus',
    'Bachus',
    'Lydian',
    'Dorius',
    'Enigmus',
    'Phrygian',
    'Ixolyd',
    'Octaton',
    'Diminus',
    'Tetrachor',
    'Monic',
    'Melodius',
    'Stravin',
    'Cravenous',
    'Ravus',
    'Belius',
    'Zemlin',
    'Roko',
    'Korsak',
    'Rheif',
    'Koldrus',
    'Pardus',
    'Tigris',
    'Felis',
    'Chaus',
    'Zenoch',
    'Deous',
    'Farious',
    'Trocious',
    'Pravitous',
    'Flagitious',
    'Zastor',
    'Brute',
    'Bane',
    'Enormous',
    'Bolical',
    'Beast',
    'Viol',
    'Bor',
    'Hemoth',
    'Heth',
    'Crimous',
    'Viathan',
    'Vader',
    'Sidious',
    'Scabrous',
    'Nix',
    'Chimerant',
    'Spectrus',
    'Rageous',
    'Whelm',
    'Ignis',
    'Ceptus',
    'Lacious',
    'Tazimous',
    'Vaporous',
    'Tern',
    'Digo',
    'Letch',
    'Dicator',
    'Hibitor',
    'Nocent',
    'Crement',
    'Tersect',
    'Jurious',
    'Ventor',
    'Carnate',
    'Carnous',
    'Dulgeous',
    'Fector',
    'Sular',
    'Trudor',
    'Terim',
    'Zade',
    'Zound',
    'Cipher',
    'Crypt',
    'Null',
    'Nought',
    'Naught',
    'Vigor',
    'Cault',
    'Phyrious',
    'Furious',
    'Emminous',
    'Voker',
    'Quire',
    'Spire',
    'Rive',
    'Blathe',
    'Murthe',
    'Psythe',
    'Staber',
    'Dagous',
    'Vagueus',
    'Plagueis',
    'Mageus',
    'Kyther',
    'Ryther',
    'Wreve',
    'Revan',
    'Plosive',
    'Bollot',
    'Krathe',
    'Rothe',
    'Nachus',
    'Prive',
    'Siccant',
    'Onus',
    'Opus',
    'Drought',
    'Faminous',
    'Coupage',
    'Exterous',
    'Ixigol',
    'Nizer',
    'Risive',
    'Hexagator',
    'Hexus',
    'Zardous',
    'Niabol',
    'Corous',
    'Ceiver',
    'Vious',
    'Modus',
    'Vilerous',
    'Zire',
    'Zirous',
    'Luxor',
    'Miser',
    'Ixis',
    'Fang',
    'Vault',
    'Hault',
    'Gaunt',
    'Skult',
    'Skulk',
    'Pulver',
    'Haulk',
    'Stachious',
    'Eaver',
    'Reather',
    'Trathe',
    'Mur',
    'Xoxus',
    'Noxus',
    'Feth',
    'Nazer',
    'Deco',
    'Faminus',
    'Phenomus',
    'Bruthe',
    'Tyrious',
    'Tyranus',
    'Stegos',
    'Ceratus',
    'Velocis',
    'Zenos',
    'Gantos',
    'Sognathus',
    'Ryonyx',
    'Tyros',
    'Karnos',
    'Rythos',
    'Cavenous',
    'Graveous',
    'Draconyx',
    'Skarious',
    'Strave',
    'Nodon',
    'Kol',
    'Kosmious',
    'Tundus',
    'Salivik',
    'Zannah',
    'Zeggah',
    'Zader',
    'Juliek',
    'Phobos',
    'Arachnis',
    'Siberus',
    'Sanguis',
    'Vectivus',
    'Venamis',
    'Kiah',
    'Maleval',
    'Malak',
    'Jerra',
    'Stryfe',
    'Stabi',
    'Pulver',
    'Havok',
    'Vok',
    'Voker',
    'Exorak',
    'Segre',
    'Noctyss',
    'Nix',
    'Nihilus',
    'Balatros',
    'Gluxigol',
    'Tessera',
    'Ghauler',
    'Hagueis',
    'Ramage',
    'Caedus',
    'Theteis',
    'Nithopsis',
    'Lokist',
    'Zhevare',
    'Raptos',
    'Pyrus',
    'Arcidius',
    'Phaganax',
    'Thagomus',
    'Stavin',
    'Stalis',
    'Titanous',
    'Venan',
    'Xixian',
    'Sydon',
    'Stygeous',
    'Tuberous',
    'Kanderous',
    'Thelix',
    'Leotrous',
    'Buke',
    'Ilex',
    'Mandrak',
    'Whyrm',
    'Rhodious',
    'Strychnous',
    'Taxus',
    'Maxus',
    'Naber',
    'Daghor',
    'Foxus',
    'Noxus',
    'Voxious',
    'Chlostros',
    'Gob',
    'Cnidar',
    'Chiron',
    'Fangor',
    'Gorious',
    'Plicitous',
    'Sacious',
    'Grever',
    'Erratus',
    'Tathe',
    'Therak',
    'Kymion',
    'Crazha',
    'Psadus',
    'Masoch',
    'Dominix',
    'Malthux',
    'Whizer',
    'Rhoth',
    'Lukrous',
    'Momen',
    'Ghrecheous',
    'Cherous',
    'Iki',
    'Ensanious',
    'Izigol',
    'Motocrous',
    'Mercilous',
    'Bellus',
    'Kilge',
    'Natrix',
    'Fessor',
    'Crazus',
    'Vanet',
    'Evious',
    'Makina',
    'Malachor',
    'Moraband',
    'Korribus',
    'Ziost',
    'Thulus',
    'Malice',
    'Rancorous',
    'Vitrious',
    'Terre',
    'Ghast',
    'Hellous',
    'Severn',
    'Aggrus',
    'Phobious',
    'Xoxus',
    'Misophsis',
    'Bhorr',
    'Stilitous',
    'Vidious',
    'Durzin',
    'Vicius',
    'Spidure',
    'Avaris',
    'Vengeous',
    'Murdrus',
    'Derus',
    'Voral',
    'Pacious',
    'Hensibol',
    'Thetik',
    'Sideret',
    'Torius',
    'Cynik',
    'Spiser',
    'Rocious',
    'Livious',
    'Vulgate',
    'Verlor',
    'Gressor',
    'Tacker',
    'Monger',
    'Cader',
    'Sailant',
    'Azgulus',
    'Sequious',
    'Volter',
    'Ghastus',
    'Kleptus',
    'Bezzler',
    'Tormant',
    'Xiete',
    'Panik',
    'Cern',
    'Qualm',
    'Lamitous',
    'Thorn',
    'Thork',
    'Thorik',
    'Thoro',
    'Zorn',
    'Zorrious',
    'Zorus',
    'Vorus',
    'Vorn',
    'Vorious',
    'Vengol',
    'Onus',
    'Opus',
    'Drought',
    'Rhetan',
    'Anguish',
    'Pain',
    'Avalanx',
    'Tastroph',
    'Bider',
    'Stalker',
    'Charrik',
    'Raastbit',
    'Tesque',
    'Thetriarch',
    'Driax',
    'Furrow',
    'Exoth',
    'Goligol',
    'Frauzt',
    'Staurm',
    'Gaal',
    'Dascious',
    'Hyve',
    'Swyrm',
    'Immolus',
    'Burninator',
    'Jeerius',
    'Machious',
    'Kophonos',
    'Pandimous',
    'Laulus',
    'Scaaf',
    'Mizri',
    'Sondius',
    'Norrid',
    'Lurryd',
    'Othlyss',
    'Xistential',
    'Purient',
    'Prudent',
    'Quaver',
    'Wrestus',
    'Ragnorus',
    'Clypsus',
    'Sykniss',
    'Laavlyss',
    'Taver',
    'Ravik',
    'Ultix',
    'Harlus',
    'Vikariot',
    'Viber',
    'Wasteous',
    'Pterassus',
    'Xadious',
    'Thraxus',
    'Yuxer',
    'Draver',
    'Zuvre',
    'Ferion',
    'Habeus',
    'Corpus',
    'Adamancis',
    'Aurodious',
    'Belligerix',
    'Calibus',
    'Chaleaux',
    'Decimet',
    'Erotis',
    'Fornix',
    'Fuul',
    'Fortis',
    'Gravitous',
    'Grandious',
    'Hazaar',
    'Hostilus',
    'Izar',
    'Jokkus',
    'Korruptus',
    'Lustillus',
    'Modalous',
    'Nether',
    'Ookious',
    'Odious',
    'Priver',
    'Quader',
    'Reezer',
    'Ronious',
    'Stereosk',
    'Terrous',
    'Uthern',
    'Vincer',
    'Viron',
    'Wyvernous',
    'Wyrm',
    'Wyyrd',
    'Xandov',
    'Xebrous',
    'Xane',
    'Yeul',
    'Zrazicus',
    'Zwalik',
    'Appetice',
    'Blight',
    'Crathe',
    'Demond',
    'Diamox',
    'Ether',
    'Evikast',
    'Fjorn',
    'Ghash',
    'Hilk',
    'Ignious',
    // `JlkwKopx`,
    'Jareth',
    'Karath',
    'Lavel',
    'Maladous',
    'Nevermour',
    'Odox',
    'Pilfur',
    'Quizik',
    'Rotash',
    'Slaink',
    'Trusk',
    'Ulgol',
    'Valker',
    'Wintious',
    'Xogog',
    'Yodrexus',
    'Zulius',
]

const darthEpithets = [
    'the Wise',
    'the Gilded',
    'the Unshorn',
    'the Forsaken',
    'the Infidel',
    'the Bloody',
    'the Bloodless',
    'the Accursed',
    'the Twice-Cursed',
    'Thrice-Cursed',
    'the Blind',
    'the Bold',
    'the Foolish',
    'the Chaste',
    'the Conqueror',
    'the Cruel',
    'the Bearded',
    'the Beardless',
    'the Beautiful',
    'the Damned',
    'the Scarred',
    'the Fortunate',
    'the Ill-Fortuned',
    'the Fair',
    'Thrice-Dead',
    'the Holy Vessel',
    'the Learned',
    'the Judge',
    'the Magnificent',
    'the Mighty',
    'the Merciful',
    'the Unmerciful',
    'the Astrogator',
    'the Mad',
    'the Pious',
    'the Prudent',
    'the Proud',
    'the Ancient',
    'the Elder',
    'the Younger',
    'the Posthumous',
    'the Rash',
    'the Red',
    'the Humiliated',
    'the Silent',
    'of Exogol',
    'of Malachor',
    'of the Throne',
    'the Stout',
    'the Terrible',
    'the Wild',
    'the Free',
    'the White',
    'the Aggressor',
    'the Alchemist',
    'the High Alchemist',
    'the Great',
    'the Greater',
    'the Lesser',
    'the Sleeping',
    'of the Deep',
    'of the Mount',
    'of the Core',
    'of the Shade',
    'of the Pit',
    'of the Storms',
    'the Boneless',
    'the Brash',
    'the Beastly',
    'the Braggart',
    'the Worse',
    'the Worst',
    'the Fallen',
    'the Unvanquished',
    'the Unseen',
    'the Singer',
    'the Eloquent',
    'the Once-Forgotten',
    'the Exile',
    'the Grim',
    'Krayt-Slayer',
    'Jedi-Slayer',
    'the Evangelist',
    'the Heartless',
    'the Hopeless',
    'the Once-Patient',
    'the Fiery',
    'the Furious',
    'the Impatient',
    'the Patient',
    'Kyber-Crusher',
    'the Invincible',
    'the Cold-Hearted',
    'the Last',
    'the First',
    'the Second',
    'the First and Last',
    'the Lawgiver',
    'the Lover',
    'the Loveless',
    'the Heartbroken',
    'the Weeping',
    'the Prophet',
    'the Seer',
    'the Oracle',
    'Peacebringer',
    'the Poet',
    'of Legend',
    'the Many-Eyed',
    'the Many-Toothed',
    'the Fanged',
    'the Treacherous',
    'the Tyrant',
    'the Caped',
    'the Cloaked',
    'of the Cowl',
    'the Wicked',
    'the Prescient',
    'the Unshorn',
]