"use strict";

const darths = [
    'Anthelion',
    'Cisor',
    'Trudor',
    'Fernus',
    'Vestis',
    'Carceret',
    'Despotes',
    'Victus',
    'Cruxis',
    'Domitus',
    'Dustrius',
    'Fensus',
    'Flexus',
    'Visus',
    'Iratus',
    'Scivious',
    'Scarlot',
    'Valdis',
    'Holst',
    'Vanger',
    'Tchaiko',
    'Desch',
    'Kaber',
    'Amadius',
    'Hoven',
    'Shern',
    'Ghulus',
    'Bachus',
    'Lydian',
    'Dorius',
    'Enigmus',
    'Phrygian',
    'Ixolyd',
    'Octaton',
    'Diminus',
    'Tetrachor',
    'Monic',
    'Melodius',
    'Stravin',
    'Cravenous',
    'Ravus',
    'Belius',
    'Zemlin',
    'Roko',
    'Korsak',
    'Rheif',
    'Koldrus',
    'Pardus',
    'Tigris',
    'Felis',
    'Chaus',
    'Zenoch',
    'Deous',
    'Farious',
    'Trocious',
    'Pravitous',
    'Flagitious',
    'Zastor',
    'Brute',
    'Bane',
    'Enomous',
    'Bolical',
    'Beast',
    'Viol',
    'Bor',
    'Hemoth',
    'Heth',
    'Crimous',
    'Viathan',
    'Vader',
    'Sidious',
    'Scabrous',
    'Nix',
    'Chimerant',
    'Spectrus',
    'Rageous',
    'Whelm',
    'Ignis',
    'Ceptus',
    'Lacious',
    'Tazimous',
    'Vaporous',
    'Tern',
    'Digo',
    'Letch',
    'Dicator',
    'Hibitor',
    'Nocent',
    'Crement',
    'Tersect',
    'Jurious',
    'Ventor',
    'Carnate',
    'Carnous',
    'Dulgeous',
    'Fector',
    'Sular',
    'Trudor',
    'Terim',
    'Zade',
    'Zound',
    'Cipher',
    'Crypt',
    'Null',
    'Nought',
    'Naught',
    'Vigor',
    'Cault',
    'Phyrious',
    'Furious',
    'Emminous',
    'Voker',
    'Quire',
    'Spire',
    'Rive',
    'Blathe',
    'Murthe',
    'Psythe',
    'Staber',
    'Dagous',
    'Vagueus',
    'Plagueis',
    'Mageus',
    'Kyther',
    'Ryther',
    'Wreve',
    'Revan',
    'Plosive',
    'Bollot',
    'Krathe',
    'Rothe',
    'Nachus',
    'Prive',
    'Siccant',
    'Prave',
    'Coupage',
    'Exterous',
    'Ixigol',
    'Nizer',
    'Risive',
    'Hexagator',
    'Hexus',
    'Zardous',
    'Niabol',
    'Corous',
    'Ceiver',
    'Vious',
    'Modus',
    'Vilerous',
    'Zire',
    'Zirous',
    'Luxor',
    'Miser',
    'Ixis',
    'Fang',
    'Vault',
    'Hault',
    'Gaunt',
    'Skult',
    'Skulk',
    'Pulver',
    'Haulk',
    'Stachious',
    'Eaver',
    'Reather',
    'Trathe',
    'Mur',
    'Toxus',
    'Noxus',
    'Feth',
    'Nazer',
    'Deco',
    'Faminus',
    'Phenomus',
    'Bruthe',
    'Tyrious',
    'Tyranus',
    'Stegos',
    'Ceratus',
    'Velocis',
    'Zenos',
    'Gantos',
    'Sognathus',
    'Ryonyx',
    'Tyros',
    'Karnos',
    'Rythos',
    'Cavenous',
    'Graveous',
    'Draconyx',
    'Skarious',
    'Strave',
    'Nodon',
    'Kol',
    'Kosmious',
    'Tundus',
    'Salivik',
    'Zannah',
    'Zeggah',
    'Zader',
    'Juliek',
    'Phobos',
    'Arachnis',
    'Siberus',
    'Sanguis',
    'Vectivus',
    'Venamis',
    'Kiah',
    'Maleval',
    'Malak',
    'Jerra',
    'Stryfe',
    'Stabi',
    'Pulver',
    'Havok',
    'Vok',
    'Voker',
    'Exorak',
    'Segre',
    'Noctyss',
    'Nix',
    'Nihilus',
    'Balatros',
    'Gluxigol',
    'Tessera',
    'Ghauler',
    'Hagueis',
    'Ramage',
    'Caedus',
    'Theteis',
    'Nithopsis',
    'Lokist',
    'Zhevare',
    'Raptos',
    'Pyrus',
    'Arcidius',
    'Phaganax',
    'Thagomus',
    'Stavin',
    'Stalis',
    'Titanous',
    'Venan',
    'Xixian',
    'Sydon',
    'Stygeous',
    'Tuberous',
    'Kanderous',
    'Thelix',
    'Leotrous',
    'Buke',
    'Ilex',
    'Mandrak',
    'Whyrm',
    'Rhodious',
    'Strychnous',
    'Taxus',
    'Maxus',
    'Naber',
    'Daghor',
    'Foxus',
    'Noxus',
    'Voxious',
    'Chlostros',
    'Gob',
    'Cnidar',
    'Chiron',
    'Fangor',
    'Gorious',
    'Plicitous',
    'Sacious',
    'Grever',
    'Erratus',
    'Tathe',
    'Therak',
    'Kymion',
    'Crazha',
    'Psadus',
    'Masoch',
    'Dominix',
    'Malthux',
    'Whizer',
    'Rhoth',
    'Lukrous',
    'Momen',
    'Ghrecheous',
    'Cherous',
    'Iki',
    'Ensanious',
    'Aisigol',
    'Motocrous',
    'Mercilous',
    'Bellus',
    'Kilge',
    'Natrix',
    'Fessor',
    'Crazus',
    'Vanet'
]

const darthEpithets = [
    'the Wise',
    'the Gilded',
    'the Foul',
    'the Forsaken',
    'the Infidel',
    'the Bloody',
    'the Bloodless',
    'the Accursed',
    'the Twice-Cursed',
    'Thrice-Cursed',
    'the Blind',
    'the Bold',
    'the Foolish',
    'the Chaste',
    'the Conqueror',
    'the Cruel',
    'the Bearded',
    'the Beautiful',
    'the Damned',
    'the Scarred',
    'the Fortunate',
    'the Ill-Fortuned',
    'the Fair',
    'Thrice-Dead',
    'the Holy Vessel',
    'the Learned',
    'the Judge',
    'the Magnificent',
    'the Mighty',
    'the Merciful',
    'the Unmerciful',
    'the Astrogator',
    'the Mad',
    'the Pious',
    'the Prudent',
    'the Proud',
    'the Ancient',
    'the Elder',
    'the Younger',
    'the Posthumous',
    'the Rash',
    'the Red',
    'the Humiliated',
    'the Silent',
    'of Exogol',
    'of Malachor',
    'of the Throne',
    'the Stout',
    'the Terrible',
    'the Wild',
    'the Free',
    'the White',
    'the Aggressor',
    'the Alchemist',
    'the High Alchemist',
    'the Great',
    'the Greater',
    'the Lesser',
    'the Sleeping',
    'of the Deep',
    'of the Mount',
    'of the Core',
    'of the Shade',
    'of the Pit',
    'of the Storms',
    'the Boneless',
    'the Brash',
    'the Beastly',
    'the Braggart',
    'the Worse',
    'the Worst',
    'the Fallen',
    'the Unvanquished',
    'the Unseen',
    'the Singer',
    'the Eloquent',
    'the Once-Forgotten',
    'the Exile',
    'the Grim',
    'Krayt-Slayer',
    'Jedi-Slayer',
    'the Evangelist',
    'the Heartless',
    'the Hopeless',
    'the Once-Patient',
    'the Fiery',
    'the Furious',
    'the Impatient',
    'the Patient',
    'Kyber-Crusher',
    'the Invincible',
    'the Cold-Hearted',
    'the Last',
    'the First',
    'the Second',
    'the First and Last',
    'the Lawgiver',
    'the Lover',
    'the Loveless',
    'the Heartbroken',
    'the Weeping',
    'the Prophet',
    'the Seer',
    'the Oracle',
    'Peacebringer',
    'the Poet',
    'of Legend',
    'the Many-Eyed',
    'the Many-Toothed',
    'the Fanged',
    'the Treacherous',
    'the Tyrant',
    'the Caped',
    'the Cloaked',
    'of the Cowl',
    'the Wicked',
    'the Prescient',
    'the Almighty',
]

const obis = [
    // 'Obi',
    // 'Wan',
    // 'Qui',
    // 'Gon',
    // 'Din',
    // 'Ken',

    'Aba',
    'Ada',
    'Aga',
    'Aka',
    'Ala',
    'Ama',
    'Ana',
    'Apa',
    'Ara',
    'Asa',
    'Atsa',
    'Ata',
    'Ava',
    'Awa',
    'Aza',

    'Abi',
    'Adi',
    'Agi',
    'Aki',
    'Ali',
    'Ami',
    'Ani',
    'Api',
    'Ari',
    'Asi',
    'Atsi',
    'Ati',
    'Avi',
    'Awi',
    'Azi',
    
    // 'Abo',
    'Addo',
    'Ago',
    'Ako',
    'Alo',
    'Amo',
    'Ano',
    'Apo',
    'Aro',
    // 'Aso',
    'Atso',
    'Ato',
    'Avo',
    'Awo',
    'Azo',
    
    'Oba',
    'Oda',
    'Oga',
    'Oka',
    'Ola',
    'Oma',
    'Ona',
    'Opa',
    'Ora',
    'Osa',
    'Otsa',
    'Ota',
    // 'Ova',
    'Owa',
    'Oza',

    'Obi',
    'Odi',
    'Ogi',
    'Oki',
    'Oli',
    'Omi',
    'Oni',
    'Opi',
    'Ori',
    'Osi',
    'Otsi',
    'Oti',
    'Ovi',
    // 'Owi',
    'Ozi',
    
    'Obo',
    'Odo',
    'Ogo',
    'Oko',
    'Olo',
    'Omo',
    'Ono',
    'Opo',
    'Oro',
    'Oso',
    'Otso',
    'Oto',
    'Ovo',
    // 'Owo',
    'Ozo',


    'Iba',
    'Ida',
    'Iga',
    'Ika',
    'Ila',
    'Ima',
    'Ina',
    'Ipa',
    'Ira',
    'Isa',
    'Itsa',
    'Ita',
    'Iva',
    'Iwa',
    'Iza',

    'Ibi',
    'Idi',
    'Igi',
    'Iki',
    'Ili',
    'Imi',
    'Ini',
    'Ipi',
    'Iri',
    'Isi',
    'Itsi',
    'Iti',
    'Ivi',
    'Iwi',
    'Izi',
    
    'Ibo',
    'Ido',
    'Igo',
    'Iko',
    'Ilo',
    'Imo',
    'Ino',
    'Ipo',
    'Iro',
    'Iso',
    'Itso',
    'Ito',
    'Ivo',
    'Iwo',
    'Izo',
];

const wans = [
    'Wan',
    'Win',
    'Wen',
    'Won',

    'Ban',
    'Bin',
    'Ben',
    'Bon',
    // 'Boon',

    'Dan',
    'Din',
    'Den',
    'Don',
    // 'Doon',

    'Fan',
    'Fin',
    'Fen',
    'Fon',
    // 'Foon',

    // 'Gan',
    // 'Gin',
    'Genn',
    'Gon',
    // 'Gun',

    'Han',
    // 'Hinn',
    'Hen',
    'Hon',
    // 'Ho',

    'Jan',
    'Jinn',
    'Jen',
    'Jon',
    // 'June',

    'Kan',
    'Kin',
    'Ken',
    'Kon',

    // 'Khan',
    // 'Khin',
    // 'Khen',
    // 'Khon',

    'Lan',
    'Lin',
    'Len',
    'Lon',

    // 'Mon',
    'Min',
    'Men',
    'Maun',

    // 'Nan',
    'Nin',
    'Nen',
    // 'Non'

    'Pan',
    'Piin',
    'Pin',
    'Pen',
    'Pon',

    'Quan',
    'Quin',
    'Quen',
    'Quon',

    'Ran',
    'Rin',
    'Ren',
    'Ron',

    'San',
    'Sinn',
    'Sen',
    'Son',

    'Shan',
    'Shin',
    'Shen',
    'Shon',

    'Tan',
    'Tin',
    'Tiin',
    'Ten',
    'Taun',
    // 'Toon',

    'Van',
    'Vin',
    'Ven',
    'Von',

    'Wan',
    'Win',
    'Wen',
    'Won',

    'Yan',
    'Yin',
    'Yen',
    'Yon',

    'Zan',
    'Zin',
    'Zen',
    'Zon',
];

const dis = [
    'Ba',
    'Da',
    'Fa',
    'Ga',
    'Ha',
    'Ja',
    'Ka',
    // 'Kha',
    'La',
    'Ma',
    'Na',
    'Pa',
    'Qua',
    'Ra',
    'Sa',
    'Sha',
    'Ta',
    'Va',
    'Wa',
    'Za',

    'Bi',
    'Di',
    'Fi',
    'Gi',
    'Hi',
    'Ji',
    'Ki',
    // 'Khi',
    'Li',
    'Mi',
    'Ni',
    // 'Oi',
    'Pi',
    'Qui',
    'Ri',
    'Si',
    'Shi',
    'Ti',
    'Vi',
    'Wi',
    'Zi',

    'Be',
    'Bee',
    'De',
    'Dee',
    'Fe',
    'Ge',
    'He',
    'Je',
    'Jee',
    'Ke',
    // 'Khe',
    'Le',
    'Lee',
    'Me',
    'Ne',
    'Nee',
    'Pe',
    'Ree',
    'See',
    'She',
    'Te',
    'Tee',
    'Ve',
    'Ve',
    'We',
    'Wee',
    'Ze',
    'Zee',

    // 'Bae',
    'Dae',
    // 'Fae',
    'Gae',
    // 'Hae',
    // 'Jae',
    'Kae',
    // 'Khae',
    // 'Lae',
    'Mae',
    'Nae',
    'Pae',
    // 'Quae',
    'Rae',
    'Sae',
    // 'Shae',
    'Tae',
    // 'Vae',
    // 'Wae',
    'Zae',

    'Bo',
    'Do',
    'Fo',
    'Go',
    'Ho',
    'Jo',
    'Ko',
    // 'Kho',
    'Lo',
    'Mo',
    'No',
    'Po',
    'Quo',
    'Ro',
    'Rho',
    'So',
    'Sho',
    'To',
    'Vo',
    'Wo',
    'Zo',

    'Bu',
    'Du',
    'Fu',
    'Gu',
    'Hu',
    'Ju',
    'Ku',
    // 'Kho',
    'Lu',
    'Mu',
    'Nu',
    'Pu',
    // 'Quoo',
    'Ru',
    // 'Rhoo',
    'Soo',
    'Shu',
    'Tu',
    'Vu',
    'Wu',
    'Zu',
]

const maces = [
    'Ace',
    'Bace',
    'Brace',
    'Blace',
    'Chace',
    'Clace',
    'Dace',
    'Drace',
    'Glace',
    // 'Grace',
    'Hace',
    'Jace',
    'Kace',
    'Krace',
    // 'Klace',
    // 'Lace',
    'Mace',
    'Nace',
    'Pace',
    'Prace',
    'Quace',
    // 'Race',
    // 'Sace',
    'Shace',
    'Tace',
    'Trace',
    'Vace',
    'Vlace',
    // 'Wace'
    // 'Wrace'
    // 'Xace',
    // 'Yace',
    // 'Zace',

    // 'Ass',
    // 'Bass',
    // 'Brass',
    // 'Blass',
    'Chass',
    'Class',
    'Dass',
    'Drass',
    // 'Glass',
    // 'Grass',
    'Hass',
    'Jass',
    'Kass',
    // 'Krass',
    // 'Klass',
    // 'Lass',
    // 'Mass',
    'Nass',
    // 'Pass',
    'Prass',
    // 'Quass',
    'Rass',
    // 'Sass',
    // 'Shass',
    'Tass',
    'Trass',
    'Vass',
    'Vlass',
    // 'Wass'
    'Wrass',
    'Xass',
    // 'Yass',
    'Zass',

    // 'Aze',
    'Baze',
    // 'Braze',
    'Blaze',
    'Chaze',
    // 'Claze',
    'Daze',
    'Draze',
    // 'Glaze',
    // 'Graze',
    // 'Haze',
    'Jaze',
    'Kaze',
    'Kraze',
    'Klaze',
    'Laze',
    'Maze',
    'Naze',
    'Paze',
    // 'Praze',
    // 'Quaze',
    'Raze',
    'Saze',
    // 'Taze',
    'Traze',
    // 'Vaze',
    'Vlaze',
    // 'Waze',
    'Wraze',
    // 'Xaze',
    'Yaze',
    'Zaze',

    'Ax',
    'Bax',
    'Brax',
    // 'Blax',
    'Chax',
    'Clax',
    'Dax',
    'Drax',
    'Glax',
    'Grax',
    'Hax',
    'Jax',
    'Kax',
    // 'Krax',
    'Klax',
    // 'Lax',
    'Max',
    'Nax',
    'Pax',
    'Prax',
    'Quax',
    'Rax',
    // 'Sax',
    'Tax',
    // 'Trax',
    // 'Vax',
    'Vlax',
    // 'Wax',
    'Wrax',
    // 'Xax',
    'Yax',
    'Zax',

    // 'Ale',
    // 'Bale',
    'Brael',
    // 'Blale',
    'Chael',
    // 'Clale',
    'Dael',
    'Drael',
    // 'Glale',
    'Grael',
    'Hael',
    // 'Jael',
    'Kael',
    // 'Krael',
    // 'Klael',
    // 'Lael',
    'Mael',
    'Nael',
    'Pael',
    // 'Prael',
    // 'Quael',
    'Rael',
    // 'Sael',
    // 'Tael',
    // 'Trael',
    'Vael',
    // 'Vlael',
    // 'Wael',
    // 'Wrael',
    // 'Xael',
    // 'Yael',
    'Zael',

    'Ash',
    // 'Bash',
    // 'Brash',
    'Blash',
    'Chash',
    // 'Clash',
    'Dash',
    'Drash',
    'Glash',
    'Grash',
    // 'Hash',
    'Jash',
    // 'Kash',
    // 'Krash',
    // 'Klash',
    // 'Lash',
    // 'Mash',
    // 'Nash',
    'Pash',
    'Prash',
    'Quash',
    // 'Rash',
    // 'Sash',
    'Tash',
    // 'Trash',
    // 'Vash',
    // 'Vlash',
    // 'Wash',
    // 'Wrash',
    // 'Xash',
    'Yash',
    // 'Zash',


    // 'Ece',
    'Breese',
    // 'Bleece',
    // 'Cheece',
    // 'Cleece',
    // 'Deece',
    'Dreese',
    'Gleese',
    // 'Grace',
    // 'Heece',
    // 'Jeece',
    'Keese',
    'Kreese',
    // 'Klace',
    // 'Lace',
    // 'Meese',
    'Neese',
    // 'Peese',
    // 'Preece',
    // 'Queece',
    'Reece',
    // 'Seece',
    // 'Sheece',
    'Teese',
    'Treece',
    'Veece',
    // 'Vleece',
    // 'Weece'
    // 'Wreece'
    // 'Xeece',
    // 'Yeese',
    // 'Zeace',

    // 'Ess',
    // 'Bess',
    'Bress',
    // 'Bless',
    // 'Chess',
    'Cless',
    'Des',
    // 'Dress',
    // 'Glass',
    'Gress',
    'Hes',
    'Jes',
    'Kess',
    'Kress',
    'Kless',
    'Les',
    'Mes',
    'Ness',
    'Pess',
    // 'Pres',
    'Quess',
    'Ress',
    // 'Sess',
    'Shess',
    // 'Tess',
    'Tress',
    'Ves',
    // 'Vless',
    'Wes',
    'Wress',
    'Xess',
    // 'Yess',
    'Zes',

    // 'Eze',
    'Beez',
    // 'Breeze',
    'Bleze',
    // 'Cheze',
    'Cleez',
    // 'Deez',
    'Dreze',
    'Gleez',
    'Greez',
    'Heze',
    'Jez',
    'Keze',
    'Kreez',
    'Kleez',
    'Leeze',
    'Meeze',
    'Neez',
    // 'Peeze',
    // 'Preez',
    // 'Queeze',
    'Reez',
    'Seez',
    'Teeze',
    'Treez',
    'Veze',
    'Vleze',
    // 'Weze',
    'Wreeze',
    'Xeeze',
    // 'Yeeze',
    'Zeze',

    'Ex',
    'Bex',
    'Brex',
    // 'Blax',
    // 'Chex',
    'Clex',
    'Dex',
    'Drex',
    'Glex',
    'Grex',
    // 'Hex',
    'Jex',
    // 'Kex',
    'Krex',
    'Klex',
    'Lex',
    // 'Mex',
    'Nex',
    // 'Pex',
    'Prex',
    // 'Quex',
    'Rex',
    // 'Sex',
    // 'Tex',
    // 'Trax',
    // 'Vex',
    'Vlex',
    'Wex',
    'Wrex',
    // 'Xex',
    'Yex',
    'Zex',

    'Ele',
    'Bel',
    'Brell',
    // 'Blele',
    // 'Chell',
    // 'Clale',
    'Del',
    'Drell',
    // 'Glele',
    'Grell',
    'Heel',
    'Jeel',
    'Kell',
    'Kreel',
    // 'Kleel',
    // 'Leel',
    'Mel',
    'Nell',
    'Pell',
    'Prelle',
    // 'Quel',
    'Rell',
    'Sel',
    'Teele',
    'Trell',
    'Vel',
    // 'Vlel',
    // 'Wele',
    'Wrele',
    'Xell',
    'Yeel',
    'Zeel',

    'Eesh',
    'Besh',
    'Bresh',
    'Bleesh',
    // 'Chesh',
    // 'Clesh',
    'Deesh',
    'Dresh',
    'Gleesh',
    'Gresh',
    'Hesh',
    'Jesh',
    'Kesh',
    'Kresh',
    // 'Klesh',
    'Leesh',
    // 'Mesh',
    // 'Nesh',
    'Pesh',
    // 'Presh',
    'Quesh',
    'Resh',
    // 'Sesh',
    'Teesh',
    // 'Tresh',
    'Vesh',
    // 'Vlel',
    'Wesh',
    'Wresh',
    'Xesh',
    'Yeesh',
    'Zeesh',


    // 'Oce',
    'Brose',
    'Bloce',
    // 'Choce',
    // 'Close',
    'Dose',
    // 'Drose',
    'Glose',
    // 'Groce',
    // 'Hoce',
    // 'Jose',
    'Kose',
    'Krose',
    'Klosse',
    'Loce',
    'Mos',
    'Nos',
    'Poce',
    'Prosse',
    // 'Quosse',
    'Rosce',
    // 'Sosce',
    'Shos',
    // 'Tos',
    // 'Trose',
    // 'Veece',
    // 'Vleece',
    // 'Weece'
    // 'Wreece'
    // 'Xeece',
    // 'Yeese',
    // 'Zeace',

    'Oss',
    'Bos',
    // 'Bross',
    'Bloss',
    'Choss',
    'Closs',
    'Doss',
    // 'Dross',
    // 'Gloss',
    // 'Gress',
    // 'Hos',
    // 'Jos',
    'Koss',
    'Kross',
    'Kloss',
    // 'Los',
    'Moss',
    'Noss',
    'Poss',
    'Pross',
    // 'Quoss',
    // 'Ross',
    // 'Soss',
    'Shoss',
    // 'Tess',
    'Tross',
    'Voss',
    // 'Vloss',
    'Woss',
    'Wross',
    // 'Xoss',
    // 'Yess',
    'Zoss',

    // 'Oze',
    'Boze',
    // 'Broze',
    // 'Bloze',
    // 'Choze',
    'Cloze',
    // 'Doze',
    'Droze',
    // 'Gloze',
    // 'Groze',
    // 'Hoze',
    'Joze',
    'Koze',
    'Kroze',
    // 'Kloze',
    // 'Loze',
    'Moze',
    // 'Noze',
    'Poze',
    'Proze',
    // 'Quoze',
    'Rose',
    // 'Soze',
    // 'Toze',
    'Troze',
    // 'Voze',
    // 'Vleze',
    // 'Weze',
    'Wroze',
    // 'Xoze',
    // 'Yeeze',
    // 'Zoze',

    'Ox',
    'Box',
    'Brox',
    // 'Blox',
    'Chox',
    // 'Clox',
    // 'Dox',
    'Drox',
    // 'Glox',
    // 'Grox',
    'Hox',
    'Jox',
    // 'Kox',
    'Krox',
    // 'Klox',
    // 'Lox',
    'Mox',
    // 'Nox',
    // 'Pox',
    'Prox',
    // 'Quox',
    'Rox',
    // 'Sox',
    // 'Tox',
    // 'Trox',
    // 'Vox',
    'Vlox',
    'Wox',
    'Wrox',
    // 'Xox',
    // 'Yox',
    // 'Zox',

    'Ole',
    'Bol',
    'Broll',
    // 'Blole',
    'Choll',
    // 'Clole',
    'Dol',
    'Drol',
    // 'Glele',
    'Groll',
    'Hol',
    'Jol',
    'Kol',
    'Krol',
    // 'Klol',
    // 'Lol',
    'Mol',
    'Nol',
    'Pol',
    'Proll',
    'Quol',
    'Rol',
    'Sol',
    'Tole',
    // 'Trole',
    'Vol',
    // 'Vlol',
    // 'Wole',
    // 'Wrole',
    'Xol',
    'Yol',
    'Zol',

    'Osh',
    'Bosh',
    'Brosh',
    // 'Blole',
    // 'Chosh',
    // 'Clole',
    // 'Dosh',
    // 'Drosh',
    // 'Glele',
    // 'Groll',
    'Hosh',
    // 'Josh',
    'Kosh',
    'Krosh',
    // 'Klol',
    // 'Lol',
    // 'Mosh',
    // 'Nosh',
    // 'Posh',
    'Prosh',
    // 'Quosh',
    'Rosh',
    // 'Sosh',
    // 'Tosh',
    // 'Trole',
    // 'Vosh',
    // 'Vlol',
    'Wosh',
    // 'Wrole',
    // 'Xosh',
    // 'Yosh',
    'Zosh',


    // 'Oce',
    // 'Bruce',
    'Bluce',
    // 'Choce',
    'Cluce',
    // 'Duse',
    'Droose',
    // 'Gluce',
    // 'Gruse',
    // 'Huce',
    // 'Juce',
    // 'Kuce',
    // 'Kroose',
    'Kloose',
    'Luce',
    // 'Moose',
    // 'Noose',
    // 'Pooce',
    'Pruce',
    // 'Quosse',
    'Roose',
    'Susce',
    'Shuce',
    'Tuce',
    'Troose',
    // 'Vooce',
    // 'Vleece',
    'Wuce',
    // 'Wroose',
    // 'Xeece',
    // 'Yeese',
    'Zuus',

    // 'Uss',
    // 'Bus',
    'Bruss',
    'Bluss',
    'Chuss',
    // 'Cluss',
    'Dus',
    // 'Drus',
    // 'Gluss',
    // 'Gruss',
    'Huss',
    'Juss',
    'Kuss',
    'Kruss',
    'Kluss',
    'Luss',
    'Muss',
    'Nuss',
    // 'Puss',
    // 'Pruss',
    // 'Quoss',
    'Rus',
    'Sus',
    'Shuss',
    'Tus',
    // 'Trus',
    // 'Vuss',
    // 'Vloss',
    // 'Woss',
    // 'Wruss',
    // 'Xuss',
    // 'Yuss',
    'Zuss',

    // 'Oze',
    // 'Buze',
    'Bruze',
    'Blooz',
    // 'Choze',
    'Cluze',
    'Duze',
    'Druuz',
    // 'Gluze',
    // 'Groze',
    'Huze',
    // 'Juze',
    'Koze',
    'Kroze',
    'Kluze',
    // 'Loze',
    'Mooze',
    'Nuuz',
    // 'Pze',
    'Pruuz',
    // 'Quoze',
    // 'Ruuz',
    'Sooze',
    'Tooz',
    'Truze',
    // 'Vooz',
    'Vlooz',
    // 'Weze',
    // 'Wruuz',
    // 'Xoze',
    // 'Yuze',
    'Zuze',

    'Ux',
    'Bux',
    'Brux',
    // 'Blox',
    'Chux',
    // 'Clox',
    // 'Dox',
    'Drux',
    // 'Glox',
    'Grux',
    // 'Hux',
    'Jux',
    // 'Kox',
    // 'Krux',
    // 'Klox',
    'Lux',
    'Mux',
    'Nux',
    // 'Pox',
    // 'Prox',
    // 'Quox',
    // 'Rox',
    // 'Sox',
    // 'Tox',
    // 'Trox',
    // 'Vox',
    // 'Vlox',
    // 'Wox',
    // 'Wrox',
    // 'Xox',
    // 'Yox',
    // 'Zux',

    // 'Ule',
    'Bool',
    'Brool',
    // 'Blole',
    // 'Choll',
    // 'Clole',
    // 'Dule',
    // 'Drol',
    // 'Glele',
    // 'Groll',
    'Hool',
    // 'Jol',
    // 'Kol',
    // 'Krol',
    // 'Klol',
    // 'Lol',
    'Mool',
    'Nool',
    // 'Pool',
    'Prule',
    // 'Quool',
    // 'Rol',
    'Suil',
    // 'Tole',
    // 'Trole',
    'Vool',
    // 'Vlol',
    'Wule',
    // 'Wrole',
    'Xul',
    // 'Yol',
    // 'Zol',

    // 'Oosh',
    // 'Boosh',
    // 'Broosh',
    // 'Bluush',
    // 'Choll',
    // 'Clole',
    // 'Doosh',
    // 'Droosh',
    // 'Glele',
    'Groosh',
    // 'Hoosh',
    // 'Joosh',
    // 'Koosh',
    // 'Krol',
    // 'Klol',
    // 'Lol',
    'Moosh',
    // 'Noosh',
    // 'Poosh',
    // 'Prush',
    // 'Quool',
    'Roosh',
    // 'Soosh',
    // 'Tole',
    // 'Trole',
    // 'Vool',
    // 'Vlol',
    // 'Wule',
    // 'Wrole',
    // 'Xul',
    // 'Yol',
    // 'Zol',


    // 'Ice',
    // 'Bryce',
    // 'Blyce',
    // 'Chice',
    'Clyce',
    'Dyse',
    'Drice',
    'Glyce',
    'Guisse',
    'Grice',
    'Hyce',
    'Jice',
    'Kyce',
    // 'Kryce',
    'Klyce',
    'Lyss',
    // 'Myce',
    // 'Noose',
    'Pice',
    // 'Prce',
    // 'Quosse',
    'Rys',
    // 'Sice',
    // 'Shuce',
    // 'Tuce',
    // 'Troose',
    // 'Vooce',
    'Vlyce',
    'Wisse',
    // 'Wryse',
    // 'Xeece',
    // 'Yeese',
    'Zyce',

    // 'Iss',
    'Biss',
    // 'Briss',
    // 'Bliss',
    // 'Chiss',
    // 'Cliss',
    // 'Diss',
    'Driss',
    'Gliss',
    'Griss',
    'Hiss',
    'Jiss',
    // 'Kiss',
    'Kris',
    'Kliss',
    'Liss',
    // 'Miss',
    'Niss',
    // 'Puss',
    // 'Pruss',
    // 'Quoss',
    'Riss',
    // 'Siss',
    // 'Shuss',
    // 'Tus',
    'Triss',
    'Viss',
    'Vliss',
    'Wiss',
    'Wriss',
    // 'Xuss',
    // 'Yuss',
    // 'Zss',

    'Ize',
    'Byze',
    'Bryze',
    'Blyze',
    // 'Choze',
    'Clyze',
    // 'Dyze',
    // 'Dryz',
    'Glyze',
    // 'Grze',
    'Hize',
    // 'Jiiz',
    'Kize',
    'Kryze',
    'Klyze',
    // 'Loze',
    'Mize',
    'Nyze',
    // 'Pze',
    // 'Pryze',
    // 'Quoze',
    // 'Ruuz',
    // 'Syze',
    'Tyze',
    // 'Tryze',
    'Vize',
    'Vlyze',
    // 'Weze',
    // 'Wruuz',
    // 'Xoze',
    // 'Yuze',
    'Zyze',

    // 'Ykse',
    'Byxe',
    // 'Bryxe',
    // 'Blox',
    // 'Chyxe',
    // 'Clox',
    // 'Dox',
    // 'Dryxe',
    // 'Glox',
    // 'Grux',
    // 'Hux',
    // 'Jux',
    // 'Kox',
    // 'Krux',
    // 'Klox',
    // 'Lyxe',
    'Myxe',
    // 'Nyxe',
    // 'Pox',
    // 'Prox',
    // 'Quox',
    // 'Ryxe',
    // 'Sox',
    // 'Tox',
    'Tryxe',
    // 'Vox',
    // 'Vlox',
    // 'Wox',
    // 'Wrox',
    // 'Xox',
    // 'Yox',
    // 'Zux',

    // 'Ile',
    // 'Bile',
    'Bryle',
    // 'Blole',
    // 'Choll',
    // 'Clole',
    // 'Dule',
    // 'Drol',
    // 'Glele',
    // 'Groll',
    // 'Hl',
    // 'Jol',
    'Kyle',
    // 'Krol',
    // 'Klol',
    // 'Lol',
    'Miel',
    // 'Nyle',
    // 'Pool',
    // 'Prule',
    // 'Quool',
    // 'Rol',
    'Sile',
    // 'Tole',
    // 'Trole',
    // 'Vol',
    // 'Vlol',
    'Wyle',
    // 'Wrole',
    'Xyle',
    // 'Yol',
    'Zyle',

    // 'Yshe',
    // 'Bish',
    'Brish',
    'Blish',
    // 'Choll',
    // 'Clole',
    // 'Dule',
    'Drish',
    // 'Glele',
    'Grish',
    // 'Hl',
    // 'Jish',
    'Kish',
    'Krish',
    // 'Klol',
    // 'Lol',
    'Mish',
    'Nish',
    // 'Pool',
    // 'Prule',
    'Quish',
    'Rish',
    // 'Sile',
    // 'Tole',
    // 'Trole',
    // 'Vol',
    // 'Vlol',
    // 'Wyle',
    'Wrish',
    // 'Xyle',
    // 'Yol',
    'Zish',
]
const dus = [
    // 'Ba',
    'Da',
    // 'Fa',
    'Ga',
    // 'Ha',
    'Ja',
    'Ka',
    // 'Kha',
    'La',
    // 'Ma',
    // 'Na',
    // 'Pa',
    // 'Qua',
    // 'Ra',
    'Sa',
    'Sha',
    'Ta',
    // 'Va',
    // 'Wa',
    'Za',

    // 'Bi',
    'Di',
    // 'Fi',
    'Gi',
    // 'Hi',
    'Ji',
    'Ki',
    // 'Khi',
    'Li',
    // 'Mi',
    // 'Ni',
    // 'Oi',
    // 'Pi',
    // 'Qui',
    // 'Ri',
    'Si',
    'Shi',
    'Ti',
    // 'Vi',
    // 'Wi',
    'Zi',

    // 'Be',
    // 'Bee',
    // 'De',
    'Dee',
    // 'Fe',
    // 'Ge',
    // 'He',
    // 'Je',
    'Jee',
    'Ke',
    'Kee',
    // 'Khe',
    // 'Le',
    // 'Lee',
    // 'Me',
    // 'Ne',
    // 'Nee',
    // 'Pe',
    // 'Ree',
    'See',
    'She',
    // 'Te',
    'Tee',
    // 'Ve',
    // 'Ve',
    // 'We',
    // 'Wee',
    'Ze',
    'Zee',

    // 'Bae',
    'Dae',
    // 'Fae',
    'Gae',
    // 'Hae',
    // 'Jae',
    'Kae',
    // 'Khae',
    // 'Lae',
    // 'Mae',
    // 'Nae',
    // 'Pae',
    // 'Quae',
    // 'Rae',
    'Sae',
    // 'Shae',
    'Tae',
    // 'Vae',
    // 'Wae',
    'Zae',

    // 'Bo',
    'Do',
    // 'Fo',
    'Go',
    // 'Ho',
    'Jo',
    'Ko',
    // 'Kho',
    // 'Lo',
    // 'Mo',
    // 'No',
    // 'Po',
    // 'Quo',
    // 'Ro',
    // 'Rho',
    'So',
    'Sho',
    'To',
    // 'Vo',
    // 'Wo',
    'Zo',

    // 'Bu',
    'Du',
    // 'Fu',
    'Gu',
    // 'Hu',
    'Ju',
    'Ku',
    // 'Kho',
    // 'Lu',
    // 'Mu',
    // 'Nu',
    // 'Pu',
    // 'Quoo',
    // 'Ru',
    // 'Rhoo',
    'Soo',
    'Shu',
    'Tu',
    // 'Vu',
    // 'Wu',
    'Zu',
]

const jediFNs = [
    'Jatt',
    'Ryfe',
    'Targo',
    'Chundan',
    'Taila',
    'Laman',
    'Blaz',
    'Grenner',
    'Poir',
    'Weedeek',
    'Firt',
    'Rish',
    'Neotch',
    'Werdell',
    'Lem',
    'Bace',
    'Mace',
    'Frizt',
    'Drekk',
    'Freega',
    'Dreenata',
    'Jort',
    'Uks',
    'Wagrash',
    'Myla',
    'Donuleo',
    'Nulen',
    'Marp',
    'Gringen',
    'Treak',
    'Psulu',
    'Psalapsa',
    'Trov',
    'Hustav',
    'Curze',
    'Droof',
    'Bouka',
    'Bairdo',
    'Villi',
    'Kour',
    'Ver',
    'Cerio',
    'Peet',
    'Gundo-Ran',
    'Drezda',
    'Erka',
    'Millon',
    'Koret',
    'Lonka',
    'Berideth',
    'Dreek',
    'Hattona',
    'Stawgatchi',
    'Kelnam',
    'Roncher',
    'Poice',
    'Gurpo',
    'Tersh',
    'Familam',
    'Weet-Shi',
    'Thoosh',
    'Chael',
    'Nalli',
    'Fythe',
    'Lahrosa',
    'Xamdam',
    'Runki',
    'Stampo',
    'Gatron',
    'Golth',
    'Crissen',
    'Zed',
    'Asher',
    'Noah',
    'Luke',
    'Rey',
    'Chit',
    'Kreedo',
];
const jediLNs = [
    'Dunebreaker',
    'Kalaan',
    'Brench',
    'Vanduil',
    'Moontamer',
    'Rotek',
    'Poshra',
    'Kyorri',
    'Haberdarro',
    'Brightshade',
    'Hydera',
    'Rednova',
    'Ikaramun',
    'Cemirro',
    'Rengshaft',
    'Cabon',
    'Sotori',
    'Jartassus',
    'Ferredala',
    'Taro',
    'Kaza',
    'Boorl',
    'Windu',
    'Duskwatcher',
    'Rainbreaker',
    'Bon',
    'Kestri',
    'Rentilles',
    'Gangibs',
    'Forjus',
    'Deekin',
    'Duckar',
    'Enchilles',
    'Tann',
    'Kiett',
    'Mazlan',
    'Blossus',
    'Fresmol',
    'Kull',
    'Borm',
    'Hatt',
    'Krabgi',
    'Girgo',
    'Loxus',
    'Hallo',
    'Quadinaros',
    'Besst',
    'Frelimmium',
    'Beenly',
    'Nobelo',
    'Tommisin',
    'Redstar',
    'Stoneminer',
    'Jungwater',
    'Lonota',
    'Fleetstorm',
    'Crup',
    'Samsee',
    'Greggiorini',
    'Orrengas',
    'Blazen',
    'Gregora',
    'Rotini',
    'Jonne'
];

const newSith = () => {
    let output = 'Darth ';
    output += darths[Math.floor(Math.random() * darths.length)];
    if (Math.random() >= .8) {
        output += ` ${darthEpithets[Math.floor(Math.random() * darthEpithets.length)]}`;
    }
    return output;
}

const newObiWan = () => {
    let dice = Math.random();
    let dice2 = Math.random();
    let dice3 = Math.random();
    let output = dice >= .4 ? `${obis[Math.floor(Math.random() * obis.length)]}`
        : `${dis[Math.floor(Math.random() * dis.length)]}`;
    if (dice2 >= .7) {
        output += dice3 >= .4 ? `${wans[Math.floor(Math.random() * wans.length)].toLowerCase()}`
            : `${dis[Math.floor(Math.random() * dis.length)].toLowerCase()}`;
    } else {            
        output += dice3 >= .4 ? `-${wans[Math.floor(Math.random() * wans.length)]}`
            : `-${dis[Math.floor(Math.random() * dis.length)]}`;
    }
    return output;
}
const newKenobiJinn = () => {
    let dice = Math.random();
    let output = `${wans[Math.floor(Math.random() * wans.length)]}`;
    output += dice >= .7 ? `${obis[Math.floor(Math.random() * obis.length)].toLowerCase()}`
        : dice >= .5 ? `${dis[Math.floor(Math.random() * dis.length)].toLowerCase()}`
        : ``;
    return output;
}
const newAnakin = () => {
    let dice = Math.random();
    let output = `${obis[Math.floor(Math.random() * obis.length)]}`;
    output += dice >= .5 ? `${dis[Math.floor(Math.random() * dis.length)].toLowerCase()}`
        : `${wans[Math.floor(Math.random() * wans.length)].toLowerCase()}`;
    return output;
}
const newDijon = () => {
    let output = `${dis[Math.floor(Math.random() * dis.length)]}${wans[Math.floor(Math.random() * wans.length)].toLowerCase()}`;
    return output;
}
const newKiAdiMundi = () => {
    let output = ``;
    output += `${dis[Math.floor(Math.random() * dis.length)]}`;
    output += `-${obis[Math.floor(Math.random() * obis.length)]}`;
    output += `-${wans[Math.floor(Math.random() * wans.length)]}${dus[Math.floor(Math.random() * dus.length)].toLowerCase()}`;
    return output;
}
const newMaceWindu = () => {
    let dice = Math.random();
    let output = ``;
    if (dice >= .85) {
        output += `${obis[Math.floor(Math.random() * obis.length)]}`;
        output += `${maces[Math.floor(Math.random() * maces.length)].toLowerCase()}`;
    } else {
        output += `${maces[Math.floor(Math.random() * maces.length)]}`;
    }
    output += ` ${wans[Math.floor(Math.random() * wans.length)]}${dus[Math.floor(Math.random() * dus.length)].toLowerCase()}`;
    return output;
}
const newMaster = (name) => {
    let dice = Math.random();
    let output = dice >= .7 ? `Master ${name}`
        : dice < .01 ? `Grandmaster ${name}`
        : name;
    return output;
}

const newJedi = () => {
    let dice = Math.random();
    let dice2 = Math.random();
    let output = '';
    if (dice >= .6) { // OBI-WAN / QUI-GON
        output += newObiWan();
        output += dice2 >= .4 ? ` ${newKenobiJinn()}`
            : dice2 >= .6 ? ` ${newAnakin()}`
            : ` ${newDijon()}`;
    } else if (dice >= .5) {
        output += newKiAdiMundi();
    } else if (dice >= .4) {
        output += newMaceWindu();
    } else {
        output += `${jediFNs[Math.floor(Math.random() * jediFNs.length)]}`;
        if (dice >= .05) {
            output += ` ${jediLNs[Math.floor(Math.random() * jediLNs.length)]}`;
        }
    }
    output = newMaster(output);
    return output;
}

const newName = (callback) => {
    let output = callback();
    let current = document.getElementById('output').innerHTML;
    document.getElementById('output').innerHTML = `${output}<br>${current}`;
}

document.getElementById('newSith').addEventListener('click', () => {
    newName(newSith);
})
document.getElementById('newJedi').addEventListener('click', () => {
    newName(newJedi);
})
